trigger:
  - main

pool:
  name: Default

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build and Package Application'
        steps:
          - task: Maven@3
            displayName: 'Build with Maven'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              options: '-DskipTests=true'

          - task: CopyFiles@2
            displayName: 'Copy WAR to Artifact Staging'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/target'
              Contents: '*.war' # <-- Changed from .jar to .war
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    jobs:
      - job: DeployJob
        displayName: 'Deploy to Local Tomcat'
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifact'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - script: |
              echo "Starting deployment to local Tomcat server..."
              TOMCAT_PATH="/opt/banking/apache-tomcat-10.1.23"
              
              WAR_FILE=$(find $(System.ArtifactsDirectory)/drop -name "*.war") # <-- Find .war file
              echo "Found WAR file: $WAR_FILE"
              
              echo "Stopping Tomcat..."
              $TOMCAT_PATH/bin/shutdown.sh
              sleep 10
              
              echo "Cleaning old application files..."
              rm -rf $TOMCAT_PATH/webapps/ROOT.war
              rm -rf $TOMCAT_PATH/webapps/ROOT
              
              echo "Copying new WAR file as ROOT.war..."
              cp $WAR_FILE $TOMCAT_PATH/webapps/ROOT.war # <-- Deploy as ROOT.war
              
              echo "Starting Tomcat..."
              $TOMCAT_PATH/bin/startup.sh
              
              echo "Deployment complete."
            displayName: 'Run Deployment Script'