trigger:
  - main

pool: Default # This must be your self-hosted agent pool

variables:
  dockerhubUsername: 'konderaju1238'
  imageName: 'library-management-system'
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: BuildAndPush
        displayName: 'Build and Push'
        steps:
          - task: Maven@3
            displayName: 'Build Spring Boot JAR'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              options: '-DskipTests=true'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              repository: '$(dockerhubUsername)/$(imageName)'
              tags: '$(tag)'
              dockerfile: 'Dockerfile'
              buildContext: '.'

          - task: Docker@2
            displayName: 'Push Image to Docker Hub'
            inputs:
              containerRegistry: 'DockerHubConnection'
              command: push
              repository: '$(dockerhubUsername)/$(imageName)'
              tags: '$(tag)'

  - stage: Deploy
    displayName: 'Deploy to Kubernetes'
    dependsOn: Build
    jobs:
      - job: DeployToK8s
        displayName: 'Deploy'
        steps:
          - script: |
              echo "--- Deploying image: $(dockerhubUsername)/$(imageName):$(tag) ---"
              kubectl set image deployment/library-app-deployment library-app-container=$(dockerhubUsername)/$(imageName):$(tag) --record
              echo "--- Applying other manifests ---"
              kubectl apply -f k8s/
              echo "--- Deployment successful ---"
            displayName: 'Run kubectl commands on self-hosted agent'