trigger:
  - main

pool: Default

variables:
  dockerhubUsername: 'konderaju1238'
  imageName: 'library-management-system'
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: BuildAndPush
        displayName: 'Build and Push'
        steps:
          - task: Maven@4
            displayName: 'Build Spring Boot JAR'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              options: '-DskipTests=true'
              publishJUnitResults: false

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              repository: '$(dockerhubUsername)/$(imageName)'
              tags: '$(tag)'
              dockerfile: 'Dockerfile'
              buildContext: '.'
              arguments: '--no-cache'

          - task: Docker@2
            displayName: 'Push Image to Docker Hub'
            inputs:
              containerRegistry: 'DockerHubConnection'
              command: push
              repository: '$(dockerhubUsername)/$(imageName)'
              tags: '$(tag)'

  - stage: Deploy
    displayName: 'Deploy to Kubernetes'
    dependsOn: Build
    jobs:
      - job: DeployToK8s
        displayName: 'Deploy'
        steps:
          # 👇 THIS SCRIPT IS NOW SIMPLER AND MORE RELIABLE
          - script: |
              echo "--- Triggering deployment with new image: $(dockerhubUsername)/$(imageName):$(tag) ---"
              kubectl set image deployment/library-app-deployment library-app-container=$(dockerhubUsername)/$(imageName):$(tag) --record
              echo "--- Rolling update initiated successfully ---"
            displayName: 'Trigger Kubernetes Rolling Update'