apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: library-app-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: library-app
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
